### ISSUE TITLE
PyMISP has no attribute 'get_object_templates_list'

### ISSUE THREAD

**Issue by dmoore44** [MISP/PyMISP#560]
I recently came across a script that will allow me to batch import objects to an event [https://github.com/geekscrapy/misp-batchobjects](url), but when I run the script, I get the following error: 

```
(me@machine:~/misp-batchobjects$) => python3 batch_objects.py -c import_me.csv -e 12345 --dryrun
Traceback (most recent call last):
  File "batch_objects.py", line 163, in <module>
    template = pymisp.get_object_templates_list()
AttributeError: 'PyMISP' object has no attribute 'get_object_templates_list'
```

In order to provide confirmation that the error is with pymisp, I tried to recreate it myself:

```
(me@machine:~/misp-batchobjects$) => python3
Python 3.7.4 (default, Sep  7 2019, 18:27:02)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 >>> from pymisp import PyMISP, MISPEvent
 >>> from pymisp.tools import GenericObjectGenerator
 >>> from pymisp.exceptions import NewAttributeError
    template = PyMISP.get_object_templates_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'PyMISP' has no attribute 'get_object_templates_list'
```

I installed pymisp earlier today via pip3:
```
(me@machine:~/misp-batchobjects$) => pip3 list
Package            Version
------------------ ----------
...
pymisp             2.4.123
...
```

**Comment by Rafiot** [comment]
Hmmm yeah, that script was developed using the old version of the API that was already deprecated at that time, and is now gone.

This script *may* still work on the release `v2.4.119.1` of PyMISP, but no promises.

**Comment by dmoore44** [comment]
Well crap. Guess its time to fork and update.

**Comment by Rafiot** [comment]
If you do, as it seems to be mostly loading a CSV and making an object out of it, I'd recommend you to look at that: https://github.com/MISP/PyMISP/blob/master/examples/load_csv.py

it may solve your problem out of the box.
